# Generated by Django 4.2.5 on 2023-10-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
