# Generated by Django 4.2.5 on 2023-10-04 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_workshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='end_time',
        ),
        migrations.AddField(
            model_name='workshift',
            name='hours',
            field=models.IntegerField(default=10),  # Poprawiona linia
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshift',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
