# Generated by Django 4.2.5 on 2023-10-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_employee_employment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSpecialization',
        ),
    ]
