# Generated by Django 4.2.5 on 2023-10-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_assignment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
