# Generated by Django 4.2.5 on 2023-10-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_place_address_place_postal_code_place_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='postal_code',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
