# Generated by Django 4.2.5 on 2023-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_place_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
