version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'aleksander.wilewski@brill.pl', 'BRill1234%') if not User.objects.filter(username='admin').exists() else 0;\" | python manage.py shell && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BRill1234%

